# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/seymo/Desktop/SDK-L

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/seymo/Desktop/SDK-L

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/seymo/Desktop/SDK-L/CMakeFiles /mnt/c/Users/seymo/Desktop/SDK-L/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/seymo/Desktop/SDK-L/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sdkv

# Build rule for target.
sdkv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdkv
.PHONY : sdkv

# fast build rule for target.
sdkv/fast:
	$(MAKE) -f CMakeFiles/sdkv.dir/build.make CMakeFiles/sdkv.dir/build
.PHONY : sdkv/fast

#=============================================================================
# Target rules for targets named sdkl

# Build rule for target.
sdkl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdkl
.PHONY : sdkl

# fast build rule for target.
sdkl/fast:
	$(MAKE) -f CMakeFiles/sdkl.dir/build.make CMakeFiles/sdkl.dir/build
.PHONY : sdkl/fast

#=============================================================================
# Target rules for targets named maintestone

# Build rule for target.
maintestone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 maintestone
.PHONY : maintestone

# fast build rule for target.
maintestone/fast:
	$(MAKE) -f CMakeFiles/maintestone.dir/build.make CMakeFiles/maintestone.dir/build
.PHONY : maintestone/fast

#=============================================================================
# Target rules for targets named sdki

# Build rule for target.
sdki: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdki
.PHONY : sdki

# fast build rule for target.
sdki/fast:
	$(MAKE) -f CMakeFiles/sdki.dir/build.make CMakeFiles/sdki.dir/build
.PHONY : sdki/fast

#=============================================================================
# Target rules for targets named spm

# Build rule for target.
spm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spm
.PHONY : spm

# fast build rule for target.
spm/fast:
	$(MAKE) -f CMakeFiles/spm.dir/build.make CMakeFiles/spm.dir/build
.PHONY : spm/fast

#=============================================================================
# Target rules for targets named sdkp

# Build rule for target.
sdkp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdkp
.PHONY : sdkp

# fast build rule for target.
sdkp/fast:
	$(MAKE) -f CMakeFiles/sdkp.dir/build.make CMakeFiles/sdkp.dir/build
.PHONY : sdkp/fast

#=============================================================================
# Target rules for targets named sdkg

# Build rule for target.
sdkg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdkg
.PHONY : sdkg

# fast build rule for target.
sdkg/fast:
	$(MAKE) -f CMakeFiles/sdkg.dir/build.make CMakeFiles/sdkg.dir/build
.PHONY : sdkg/fast

#=============================================================================
# Target rules for targets named scc

# Build rule for target.
scc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scc
.PHONY : scc

# fast build rule for target.
scc/fast:
	$(MAKE) -f CMakeFiles/scc.dir/build.make CMakeFiles/scc.dir/build
.PHONY : scc/fast

#=============================================================================
# Target rules for targets named sdko

# Build rule for target.
sdko: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdko
.PHONY : sdko

# fast build rule for target.
sdko/fast:
	$(MAKE) -f CMakeFiles/sdko.dir/build.make CMakeFiles/sdko.dir/build
.PHONY : sdko/fast

api/tests/ordered_map.o: api/tests/ordered_map.cpp.o

.PHONY : api/tests/ordered_map.o

# target to build an object file
api/tests/ordered_map.cpp.o:
	$(MAKE) -f CMakeFiles/maintestone.dir/build.make CMakeFiles/maintestone.dir/api/tests/ordered_map.cpp.o
.PHONY : api/tests/ordered_map.cpp.o

api/tests/ordered_map.i: api/tests/ordered_map.cpp.i

.PHONY : api/tests/ordered_map.i

# target to preprocess a source file
api/tests/ordered_map.cpp.i:
	$(MAKE) -f CMakeFiles/maintestone.dir/build.make CMakeFiles/maintestone.dir/api/tests/ordered_map.cpp.i
.PHONY : api/tests/ordered_map.cpp.i

api/tests/ordered_map.s: api/tests/ordered_map.cpp.s

.PHONY : api/tests/ordered_map.s

# target to generate assembly for a file
api/tests/ordered_map.cpp.s:
	$(MAKE) -f CMakeFiles/maintestone.dir/build.make CMakeFiles/maintestone.dir/api/tests/ordered_map.cpp.s
.PHONY : api/tests/ordered_map.cpp.s

compiler/compiler.o: compiler/compiler.cpp.o

.PHONY : compiler/compiler.o

# target to build an object file
compiler/compiler.cpp.o:
	$(MAKE) -f CMakeFiles/scc.dir/build.make CMakeFiles/scc.dir/compiler/compiler.cpp.o
.PHONY : compiler/compiler.cpp.o

compiler/compiler.i: compiler/compiler.cpp.i

.PHONY : compiler/compiler.i

# target to preprocess a source file
compiler/compiler.cpp.i:
	$(MAKE) -f CMakeFiles/scc.dir/build.make CMakeFiles/scc.dir/compiler/compiler.cpp.i
.PHONY : compiler/compiler.cpp.i

compiler/compiler.s: compiler/compiler.cpp.s

.PHONY : compiler/compiler.s

# target to generate assembly for a file
compiler/compiler.cpp.s:
	$(MAKE) -f CMakeFiles/scc.dir/build.make CMakeFiles/scc.dir/compiler/compiler.cpp.s
.PHONY : compiler/compiler.cpp.s

driver/dev.o: driver/dev.cpp.o

.PHONY : driver/dev.o

# target to build an object file
driver/dev.cpp.o:
	$(MAKE) -f CMakeFiles/sdkv.dir/build.make CMakeFiles/sdkv.dir/driver/dev.cpp.o
.PHONY : driver/dev.cpp.o

driver/dev.i: driver/dev.cpp.i

.PHONY : driver/dev.i

# target to preprocess a source file
driver/dev.cpp.i:
	$(MAKE) -f CMakeFiles/sdkv.dir/build.make CMakeFiles/sdkv.dir/driver/dev.cpp.i
.PHONY : driver/dev.cpp.i

driver/dev.s: driver/dev.cpp.s

.PHONY : driver/dev.s

# target to generate assembly for a file
driver/dev.cpp.s:
	$(MAKE) -f CMakeFiles/sdkv.dir/build.make CMakeFiles/sdkv.dir/driver/dev.cpp.s
.PHONY : driver/dev.cpp.s

driver/mx.o: driver/mx.cpp.o

.PHONY : driver/mx.o

# target to build an object file
driver/mx.cpp.o:
	$(MAKE) -f CMakeFiles/sdki.dir/build.make CMakeFiles/sdki.dir/driver/mx.cpp.o
.PHONY : driver/mx.cpp.o

driver/mx.i: driver/mx.cpp.i

.PHONY : driver/mx.i

# target to preprocess a source file
driver/mx.cpp.i:
	$(MAKE) -f CMakeFiles/sdki.dir/build.make CMakeFiles/sdki.dir/driver/mx.cpp.i
.PHONY : driver/mx.cpp.i

driver/mx.s: driver/mx.cpp.s

.PHONY : driver/mx.s

# target to generate assembly for a file
driver/mx.cpp.s:
	$(MAKE) -f CMakeFiles/sdki.dir/build.make CMakeFiles/sdki.dir/driver/mx.cpp.s
.PHONY : driver/mx.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/sdko.dir/build.make CMakeFiles/sdko.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/sdko.dir/build.make CMakeFiles/sdko.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/sdko.dir/build.make CMakeFiles/sdko.dir/main.cpp.s
.PHONY : main.cpp.s

misc/spm.o: misc/spm.cxx.o

.PHONY : misc/spm.o

# target to build an object file
misc/spm.cxx.o:
	$(MAKE) -f CMakeFiles/spm.dir/build.make CMakeFiles/spm.dir/misc/spm.cxx.o
.PHONY : misc/spm.cxx.o

misc/spm.i: misc/spm.cxx.i

.PHONY : misc/spm.i

# target to preprocess a source file
misc/spm.cxx.i:
	$(MAKE) -f CMakeFiles/spm.dir/build.make CMakeFiles/spm.dir/misc/spm.cxx.i
.PHONY : misc/spm.cxx.i

misc/spm.s: misc/spm.cxx.s

.PHONY : misc/spm.s

# target to generate assembly for a file
misc/spm.cxx.s:
	$(MAKE) -f CMakeFiles/spm.dir/build.make CMakeFiles/spm.dir/misc/spm.cxx.s
.PHONY : misc/spm.cxx.s

parser/grouper.o: parser/grouper.cpp.o

.PHONY : parser/grouper.o

# target to build an object file
parser/grouper.cpp.o:
	$(MAKE) -f CMakeFiles/sdkg.dir/build.make CMakeFiles/sdkg.dir/parser/grouper.cpp.o
.PHONY : parser/grouper.cpp.o

parser/grouper.i: parser/grouper.cpp.i

.PHONY : parser/grouper.i

# target to preprocess a source file
parser/grouper.cpp.i:
	$(MAKE) -f CMakeFiles/sdkg.dir/build.make CMakeFiles/sdkg.dir/parser/grouper.cpp.i
.PHONY : parser/grouper.cpp.i

parser/grouper.s: parser/grouper.cpp.s

.PHONY : parser/grouper.s

# target to generate assembly for a file
parser/grouper.cpp.s:
	$(MAKE) -f CMakeFiles/sdkg.dir/build.make CMakeFiles/sdkg.dir/parser/grouper.cpp.s
.PHONY : parser/grouper.cpp.s

projects/sdkproj-run.o: projects/sdkproj-run.cpp.o

.PHONY : projects/sdkproj-run.o

# target to build an object file
projects/sdkproj-run.cpp.o:
	$(MAKE) -f CMakeFiles/sdkp.dir/build.make CMakeFiles/sdkp.dir/projects/sdkproj-run.cpp.o
.PHONY : projects/sdkproj-run.cpp.o

projects/sdkproj-run.i: projects/sdkproj-run.cpp.i

.PHONY : projects/sdkproj-run.i

# target to preprocess a source file
projects/sdkproj-run.cpp.i:
	$(MAKE) -f CMakeFiles/sdkp.dir/build.make CMakeFiles/sdkp.dir/projects/sdkproj-run.cpp.i
.PHONY : projects/sdkproj-run.cpp.i

projects/sdkproj-run.s: projects/sdkproj-run.cpp.s

.PHONY : projects/sdkproj-run.s

# target to generate assembly for a file
projects/sdkproj-run.cpp.s:
	$(MAKE) -f CMakeFiles/sdkp.dir/build.make CMakeFiles/sdkp.dir/projects/sdkproj-run.cpp.s
.PHONY : projects/sdkproj-run.cpp.s

standards/1.0/1.0.o: standards/1.0/1.0.cpp.o

.PHONY : standards/1.0/1.0.o

# target to build an object file
standards/1.0/1.0.cpp.o:
	$(MAKE) -f CMakeFiles/sdkl.dir/build.make CMakeFiles/sdkl.dir/standards/1.0/1.0.cpp.o
.PHONY : standards/1.0/1.0.cpp.o

standards/1.0/1.0.i: standards/1.0/1.0.cpp.i

.PHONY : standards/1.0/1.0.i

# target to preprocess a source file
standards/1.0/1.0.cpp.i:
	$(MAKE) -f CMakeFiles/sdkl.dir/build.make CMakeFiles/sdkl.dir/standards/1.0/1.0.cpp.i
.PHONY : standards/1.0/1.0.cpp.i

standards/1.0/1.0.s: standards/1.0/1.0.cpp.s

.PHONY : standards/1.0/1.0.s

# target to generate assembly for a file
standards/1.0/1.0.cpp.s:
	$(MAKE) -f CMakeFiles/sdkl.dir/build.make CMakeFiles/sdkl.dir/standards/1.0/1.0.cpp.s
.PHONY : standards/1.0/1.0.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... sdkv"
	@echo "... sdkl"
	@echo "... rebuild_cache"
	@echo "... maintestone"
	@echo "... sdki"
	@echo "... spm"
	@echo "... sdkp"
	@echo "... sdkg"
	@echo "... scc"
	@echo "... sdko"
	@echo "... api/tests/ordered_map.o"
	@echo "... api/tests/ordered_map.i"
	@echo "... api/tests/ordered_map.s"
	@echo "... compiler/compiler.o"
	@echo "... compiler/compiler.i"
	@echo "... compiler/compiler.s"
	@echo "... driver/dev.o"
	@echo "... driver/dev.i"
	@echo "... driver/dev.s"
	@echo "... driver/mx.o"
	@echo "... driver/mx.i"
	@echo "... driver/mx.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... misc/spm.o"
	@echo "... misc/spm.i"
	@echo "... misc/spm.s"
	@echo "... parser/grouper.o"
	@echo "... parser/grouper.i"
	@echo "... parser/grouper.s"
	@echo "... projects/sdkproj-run.o"
	@echo "... projects/sdkproj-run.i"
	@echo "... projects/sdkproj-run.s"
	@echo "... standards/1.0/1.0.o"
	@echo "... standards/1.0/1.0.i"
	@echo "... standards/1.0/1.0.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

