# define mx

#include <fstream>

#include "drv.h"


// read and write cache to drive

int main(int argc, char * * argv) {
  /**
   * Don't allow LOGIC_ERRORS to be sent.
   */
  if (argv[1] != nullptr) return 3;
  std::string mainv = argv[1];
  
  if (mainv == "-c") {
    	std::ofstream file("SDKCache.txt");
    	file << "#=============================\n# CACHE GENERATED BY " << __FILE__ << ". DO NOT EDIT!\n#===========================\n"
																					"\n"
					 "\n"
	  "\n"
   "cache=gen";
    	file.close();
  }
}